# Crea el fitxer docker-compose.yml a l'arrel del projecte. Aquest fitxer definirà dos serveis: 
# el servidor MongoDB i el client Mongo Express per gestionar la base de dades des del navegador.

# /* 1.1 Servei MongoDB
# El servei de MongoDB ha de complir els requisits següents:

version: '3.8'

services:
  mongodb:
    image: mongo:7.0 # ● Imatge: mongo:7.0
    container_name: mongodb-tienda # ● Nom del contenidor: mongodb-botiga
    ports: # ● Port exposat: 27017 (host) → 27017 (contenidor)
      - "27017:27017"
    environment: # ● Variables d'entorn:  i 
      MONGO_INITDB_ROOT_USERNAME: david # MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: david97 # MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./fecha:/data/db # ./data a /data/db per a la persistència
      - ./mongo-init:/docker-entrypoint-initdb.d # ● Volum: muntar ./mongo-init a /docker-entrypoint-initdb.d per a la inicialització
    networks:
      - red-tienda # ● Xarxa: xarxa personalitzada (amb nom) anomenada xarxa-botiga*/
    # 1.2 Servei Mongo Express
    # Mongo Express és una interfície web per gestionar MongoDB. Ha de complir:

  mongoexpress:  # ← Dentro de services, no afuera
    image: mongo-express:1.0 # ● Imatge: mongo-express:1.0
    container_name: mongoexpress-tienda # ● Nom del contenidor: mongoexpress-botiga
    ports:        # ● Port exposat: 8081 (host) → 8081 (contenidor)
      - "8081:8081"
    depends_on: # ● Dependència: ha d'arrancar després de mongodb-botiga
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: david
      ME_CONFIG_MONGODB_ADMINPASSWORD: david97
      ME_CONFIG_MONGODB_URL: mongodb://david:david97@mongodb:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    restart: unless-stopped
    networks:
      - red-tienda 

networks:
  red-tienda:
    driver: bridge




